name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - "develop"
    tags:
      - '*'

jobs:
  tests:
    name: Tests
    container: nrel/openstudio:3.10.0
    runs-on: ubuntu-latest
    env:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        gem install bundler -v 2.4.10
        bundle config set --local path "$GITHUB_WORKSPACE/.bundle/install"
        bundle install
        bundle exec rake measures:install_external
    - name: Run Tests
      run: bundle exec rspec
